In [1]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.2.0


In [6]:
msg = tf.constant("Hello Tensorflow!")

In [7]:
tf.print(msg)

Hello Tensorflow!


# TensorFlow 数据流图是一种声明式编程器范式
|  编程范式   | 核心思想 | 程序抽象  |  计算过程  | 计算单元  | 擅长领域 |    实现方法  |
|    ----    | ----   |   ----   |   ----   |   ----   |  ----  |     ----    |
| 声明式编程  |  要什么  | 数学模型  | 表达式变换 |   函数   | 数理逻辑 | 结构化 抽象化 |
| 命令式编程  |  怎么做  | 有穷自动机|  状态转换  |   指令   | 业务逻辑 | 过程化 具体化 |

In [1]:
# 斐波拉契数列

# 声明式
fib = lambda x : 1 if x <= 2 else fib(x - 1) + fib(x - 2)

# 命令式
def fib(n):
    a, b = 1, 1
    for i in range(1, n):
        a, b = b, a + b
    return a

# TensorFlow 張量
* 在 TensorFlow 中張量（Tensor）表示某種相同數據類型的多維數組。因此，張量有兩個重要屬性：
1. 數據類型（如浮點型，整型，字符串）
2. 數組形狀（各個維度的大小）0階，1階，2階，3階・・・

## Q：張量是什麽
* 張量是用來表示多維數據的
* 張量是執行操作時的輸入或輸出的數據
* 用戶通過執行操作來創建或計算張量
* 張量的形狀不一定在編譯時確定，可以在運行時通過形狀推斷計算得出

## 在 TensorFlow 中，有几類比較特別的張量，由以下操作產生：
* tf.constant //常量
* tf.placeholder //佔位符
* tf.Variable //變量


In [3]:
# 0 階張量
mammal = tf.Variable("Elephant", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

In [4]:
[mammal, ignition, floating, its_complicated]

[<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Elephant'>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1415927>,
 <tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>]

In [5]:
# 1 階張量
mystr = tf.Variable(["Hello", "World"], tf.string)
cool_numbers = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

In [6]:
[mystr, cool_numbers, first_primes, its_very_complicated]

[<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'Hello', b'World'], dtype=object)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3.14159, 2.71828], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.85j,  7.5-6.23j])>]

In [7]:
# 2 階張量
mymat = tf.Variable([[7], [11]], tf.int16)
myxor = tf.Variable([[False, True], [True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([[4, 9], [16, 25]], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

In [8]:
[mymat, myxor, linear_squares, squarish_squares, rank_of_squares, mymatC]

[<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
 array([[ 7],
        [11]])>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=bool, numpy=
 array([[False,  True],
        [ True, False]])>,
 <tf.Variable 'Variable:0' shape=(4, 1) dtype=int32, numpy=
 array([[ 4],
        [ 9],
        [16],
        [25]])>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[ 4,  9],
        [16, 25]])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
 array([[ 7],
        [11]])>]

In [9]:
# 4 階張量
my_image = tf.zeros([10, 299, 299, 3]) # batch x height x with x color

In [13]:
# my_image

# TensorFlow 變量
* TensorFlow 變量（Variable）的主要作用是維護特定節點的狀態，如深度學習或機器學習的模型參數。
* tf.Variable 方法是操作，返回值是變量（特殊張量）
* 通過 tf.Variable 方法創建的變量，與張量一樣，可以作爲操作的輸入和輸出。不同之處在於:
    * 張量的生命周期通常隨依賴的計算完成而結束，内存也隨即釋放。
    * 變量則常駐内存，在每一步訓練時不斷更新其值，以實現模型參數的更新

# TensorFlow 操作
TensorFlow 用数据流图表示算法模型。数据流图由节点和有向边组成，每个节点均对应一个具体的操作。因此，操作是模型功能的实际载体。
数据流图中的节点按照功能不同可以分为3种
* __存储节点__ ：有状态的变量操作，通常用来存储模型参数
* __计算节点__ ：无状态的计算或控制操作，主要负责算法逻辑表达或流程控制
* __数据节点__ ：数据的占位符操作，用于描述图外输入数据的属性

## 占位符操作
TensorFlow使用占位符操作表示图外输入的数据，如训练和测试数据。
TensorFlow数据流图描述了算法模型的计算拓扑，其中的各个操作（节点）都是抽象的函数映射或数学表达式。
换句话说，数据流图本身是一个具有计算拓扑和内部结构的“壳”。在用户向数据流图填充数据前，图中并没有真正执行任何计算