# Python 基础语法

## 输入与输出

In [2]:
name = input("What's your name?")
sum = 100+100
print ('hello,%s' %name)
print ('sum = %d' %sum)

hello,Lin
sum = 200


## 判断语句：if … else …
```
if score>= 90:
       print 'Excellent'
else:
       if score < 60:
           print 'Fail'
       else:
           print 'Good Job'
```

## 循环语句：for … in

In [6]:
sum = 0
for number in range(11):
    sum = sum + number
print (sum)

55


## 循环语句: while

In [7]:
sum = 0
number = 1
while number < 11:
       sum = sum + number
       number = number + 1
print (sum)

55


## 数据类型：列表、元组、字典、集合

### 列表：[]

In [11]:
lists = ['a','b','c']
lists.append('d')
print (lists)
print (len(lists))
lists.insert(0,'mm')
lists.pop()
print (lists)

['a', 'b', 'c', 'd']
4
['mm', 'a', 'b', 'c']


### 元组 (tuple)

In [10]:
tuples = ('tupleA','tupleB')
print (tuples[0])

tupleA


### 字典 {dictionary}

In [12]:

# -*- coding: utf-8 -*
#定义一个dictionary
score = {'guanyu':95,'zhangfei':96}
#添加一个元素
score['zhaoyun'] = 98
print (score)
#删除一个元素
score.pop('zhangfei')
#查看key是否存在
print ('guanyu' in score)
#查看一个key对应的值
print (score.get('guanyu'))
print (score.get('yase',99))

{'guanyu': 95, 'zhangfei': 96, 'zhaoyun': 98}
True
95
99


### 集合：set

In [13]:
s = set(['a', 'b', 'c'])
s.add('d')
s.remove('b')
print (s)
print ('c' in s)

{'d', 'c', 'a'}
True


### 注释： ```#```

In [ ]:
# -*- coding: utf-8 -*
'''
这是多行注释，用三个单引号
这是多行注释，用三个单引号 
这是多行注释，用三个单引号
'''

### 引用模块 / 包：import

```
# 导入一个模块
import model_name
# 导入多个模块
import module_name1,module_name2
# 导入包中指定模块 
from package_name import moudule_name
# 导入包中所有模块 
from package_name import *
```

### 函数：def

In [15]:
def addone(score):
   return score + 1
print (addone(99))

100


# NumPy
列表 list 的元素在系统内存中是分散存储的，而 NumPy 数组存储在一个均匀连续的内存块中。这样数组计算遍历所有的元素，不像列表 list 还需要对内存地址进行查找，从而节省了计算资源。

在内存访问模式中，缓存会直接把字节块从 RAM 加载到 CPU 寄存器中。因为数据连续的存储在内存中，NumPy 直接利用现代 CPU 的矢量化指令计算，加载寄存器中的多个连续浮点数。另外 NumPy 中的矩阵计算可以采用多线程的方式，充分利用多核 CPU 计算资源，大大提升了计算效率。

## ndarray 对象
ndarray 实际上是多维数组的含义。在 NumPy 数组中，维数称为秩（rank），一维数组的秩为 1，二维数组的秩为 2，以此类推。在 NumPy 中，每一个线性的数组称为一个轴（axes），其实秩就是描述轴的数量。
* __ axis=0 是跨行（纵向），axis=1 是跨列（横向） __

In [18]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b[1,1]=10
print (a.shape) # 通过函数 shape 属性获得数组的大小
print (b.shape)
print (a.dtype) # 通过 dtype 获得元素的属性
print (b)

(3,)
(3, 3)
int32
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


## 结构数组

In [19]:
import numpy as np
persontype = np.dtype({ # 定义结构类型
    'names':['name', 'age', 'chinese', 'math', 'english'],
    'formats':['S32','i', 'i', 'i', 'f']})
peoples = np.array([("ZhangFei",32,75,100, 90),("GuanYu",24,85,96,88.5),
       ("ZhaoYun",28,85,92,96.5),("HuangZhong",29,65,85,100)],
    dtype=persontype) # dtype=persontype 指定结构数组的类型
ages = peoples[:]['age']
chineses = peoples[:]['chinese']
maths = peoples[:]['math']
englishs = peoples[:]['english']
print (np.mean(ages))
print (np.mean(chineses))
print (np.mean(maths))
print (np.mean(englishs))

28.25
77.5
93.25
93.75


## ufunc 运算
ufunc 是 universal function 的缩写,它能对数组中每个元素进行函数操作。NumPy 中很多 ufunc 函数计算速度非常快，因为都是采用 C 语言实现的。

## 连续数组的创建

In [22]:
x1 = np.arange(1,11,2) # arange() 类似内置函数 range()，通过指定初始值、终值、步长来创建等差数列的一维数组，默认是不包括终值的。
x2 = np.linspace(1,9,5) # linspace 是 linear space 的缩写，代表线性等分向量的含义。linspace() 通过指定初始值、终值、元素个数来创建等差数列的一维数组，默认是包括终值的。

print(x1)
print(x2)

[1 3 5 7 9]
[1. 3. 5. 7. 9.]


## 算数运算

In [26]:
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)
print (np.add(x1, x2))
print (np.subtract(x1, x2))
print (np.multiply(x1, x2))
print (np.divide(x1, x2))
print (np.power(x1, x2))
print (np.remainder(x1, x2)) # = np.mod(x1, x2)

[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


## 统计函数

### 计数组 / 矩阵中的最大值函数 amax()，最小值函数 amin()

In [27]:
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (np.amin(a))
print (np.amin(a,0)) # amin(a,0) 是延着 axis=0 轴的最小值 [1,4,7], [2,5,8], [3,6,9]
print (np.amin(a,1)) # amin(a,1) 是延着 axis=1 轴的最小值 [1,2,3], [4,5,6], [7,8,9]
print (np.amax(a))
print (np.amax(a,0))
print (np.amax(a,1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


### 统计最大值与最小值之差 ptp()

In [28]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (np.ptp(a))
print (np.ptp(a,0))
print (np.ptp(a,1))

8
[6 6 6]
[2 2 2]


### 统计数组的百分位数 percentile()
percentile() 代表着第 p 个百分位数，这里 p 的取值范围是 0-100，如果 p=0，那么就是求最小值，如果 p=50 就是求平均值，如果 p=100 就是求最大值。同样你也可以求得在 axis=0 和 axis=1 两个轴上的 p% 的百分位数

In [29]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print (np.percentile(a, 50))
print (np.percentile(a, 50, axis=0))
print (np.percentile(a, 50, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


### 统计数组中的中位数 median()、平均数 mean()

In [30]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
#求中位数
print (np.median(a))
print (np.median(a, axis=0))
print (np.median(a, axis=1))
#求平均数
print (np.mean(a))
print (np.mean(a, axis=0))
print (np.mean(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


### 统计数组中的加权平均值 average()
average() 函数可以求加权平均，加权平均的意思就是每个元素可以设置个权重，默认情况下每个元素的权重是相同的，
所以 ```np.average(a)=(1+2+3+4)/4=2.5```，
你也可以指定权重数组 ```wts=[1,2,3,4]```，
这样加权平均 ```np.average(a,weights=wts)=(1*1+2*2+3*3+4*4)/(1+2+3+4)=3.0```。

In [31]:
a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
print (np.average(a))
print (np.average(a,weights=wts))

2.5
3.0


### 统计数组中的标准差 std()、方差 var()
方差的计算是指每个数值与平均值之差的平方求和的平均值，即 ```mean((x - x.mean())** 2)```。标准差是方差的算术平方根。在数学意义上，代表的是一组数据离平均值的分散程度。所以 ```np.var(a)=1.25```, ```np.std(a)=1.118033988749895```。

In [32]:
a = np.array([1,2,3,4])
print (np.std(a))
print (np.var(a))

1.118033988749895
1.25


## NumPy 排序

In [33]:
a = np.array([[4,3,2],[2,4,1]])
print (np.sort(a))
print (np.sort(a, axis=None))
print (np.sort(a, axis=0))  
print (np.sort(a, axis=1))  

[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


# Python科学计算：Pandas

## 数据结构：Series 和 DataFrame
* __Series__ 是个 __定长的字典序列__ 。说是定长是因为在存储的时候，相当于两个 ndarray，这也是和字典结构最大的不同。因为在字典的结构里，元素的个数是不固定的。
* Series 有两个基本属性：index 和 values。在 Series 结构中，index 默认是 0,1,2,……递增的整数序列，当然我们也可以自己来指定索引，比如 ```index=[‘a’, ‘b’, ‘c’, ‘d’]```。
* __DataFrame 类型数据结构类似数据库表__ 它包括了行索引和列索引，我们可以将 DataFrame 看成是由相同索引的 Series 组成的字典类型。

In [39]:
import pandas as pd
from pandas import Series, DataFrame
x1 = Series([1,2,3,4])
x2 = Series(data=[1,2,3,4], index=['a', 'b', 'c', 'd'])
print (x1)
print (x2)

# 采用字典的方式来创建 Series
d = {'a':1, 'b':2, 'c':3, 'd':4}
x3 = Series(d)
print (x3) 

0    1
1    2
2    3
3    4
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [45]:
import pandas as pd
from pandas import Series, DataFrame
data = {'Chinese': [66, 95, 93, 90,80],'English': [65, 85, 92, 88, 90],'Math': [30, 98, 96, 77, 90]}
df1= DataFrame(data)
df2 = DataFrame(data, index=['ZhangFei', 'GuanYu', 'ZhaoYun', 'HuangZhong', 'DianWei'], columns=['English', 'Math', 'Chinese'])
print (df1)
print (df2)

Chinese  English  Math
0       66       65    30
1       95       85    98
2       93       92    96
3       90       88    77
4       80       90    90
            English  Math  Chinese
ZhangFei         65    30       66
GuanYu           85    98       95
ZhaoYun          92    96       93
HuangZhong       88    77       90
DianWei          90    90       80


## 数据导入和输出

In [ ]:
# import pandas as pd
# from pandas import Series, DataFrame
# score = DataFrame(pd.read_excel('data.xlsx'))
# score.to_excel('data1.xlsx')
# print score

## 数据清洗

1. 删除 DataFrame 中的不必要的列或行

Pandas 提供了一个便捷的方法 drop() 函数来删除我们不想要的列或行。

In [46]:
# 把“语文”这列删掉
df2 = df2.drop(columns=['Chinese'])
print(df2)

# 把“张飞”这行删掉
df2 = df2.drop(index=['ZhangFei'])
print(df2)

English  Math
ZhangFei         65    30
GuanYu           85    98
ZhaoYun          92    96
HuangZhong       88    77
DianWei          90    90
            English  Math
GuanYu           85    98
ZhaoYun          92    96
HuangZhong       88    77
DianWei          90    90


* 重命名列名 columns，让列表名更容易识别

rename(columns=new_names, inplace=True)

In [47]:
df2.rename(columns={'Chinese': 'YuWen', 'English': 'Yingyu'}, inplace = True)
print(df2)

Yingyu  Math
GuanYu          85    98
ZhaoYun         92    96
HuangZhong      88    77
DianWei         90    90


3. 去重复的值

drop_duplicates()

In [ ]:
df = df.drop_duplicates() #去除重复行

4. 格式问题

In [ ]:
# 更改数据格式
df2['Chinese'].astype('str') 
df2['Chinese'].astype(np.int64) 

# 数据间的空格
#删除左右两边空格
df2['Chinese']=df2['Chinese'].map(str.strip)
#删除左边空格
df2['Chinese']=df2['Chinese'].map(str.lstrip)
#删除右边空格
df2['Chinese']=df2['Chinese'].map(str.rstrip)

# 删除特殊符号 比如美元符号
df2['Chinese']=df2['Chinese'].str.strip('$')

# 大小写转换
#全部大写
df2.columns = df2.columns.str.upper()
#全部小写
df2.columns = df2.columns.str.lower()
#首字母大写
df2.columns = df2.columns.str.title()

# 查找空值
#哪个地方存在空值 NaN，可以针对数据表 df 进行 df.isnull()
#想知道哪列存在空值，可以使用 df.isnull().any()

## 使用 apply 函数对数据进行清洗

In [48]:
# 对 name 列的数值都进行大写转化
df['name'] = df['name'].apply(str.upper)

# 定义个函数，在 apply 中进行使用。
# 比如定义 double_df 函数是将原来的数值 *2 进行返回。然后对 df1 中的“语文”列的数值进行 *2 处理，可以写成
def double_df(x):
           return 2*x
df1[u'语文'] = df1[u'语文'].apply(double_df)

# 对于 DataFrame，我们新增两列，其中’new1’列是“语文”和“英语”成绩之和的 m 倍，'new2’列是“语文”和“英语”成绩之和的 n 倍，我们可以这样写：
def plus(df,n,m):
    df['new1'] = (df[u'语文']+df[u'英语']) * m
    df['new2'] = (df[u'语文']+df[u'英语']) * n
    return df
df1 = df1.apply(plus,axis=1,args=(2,3,)) # axis=1 代表按照列为轴进行操作，axis=0 代表按照行为轴进行操作，args 是传递的两个参数，即 n=2, m=3，在 plus 函数中使用到了 n 和 m，从而生成新的 df。

## 数据统计


In [50]:
df1 = DataFrame({'name':['ZhangFei', 'GuanYu', 'a', 'b', 'c'], 'data1':range(5)})
print (df1.describe())

data1
count  5.000000
mean   2.000000
std    1.581139
min    0.000000
25%    1.000000
50%    2.000000
75%    3.000000
max    4.000000


## 数据表合并

In [51]:
df1 = DataFrame({'name':['ZhangFei', 'GuanYu', 'a', 'b', 'c'], 'data1':range(5)})
df2 = DataFrame({'name':['ZhangFei', 'GuanYu', 'A', 'B', 'C'], 'data2':range(5)})

1. 基于指定列进行连接

In [53]:
df3 = pd.merge(df1, df2, on='name')
print(df1)
print(df2)
print(df3)

name  data1
0  ZhangFei      0
1    GuanYu      1
2         a      2
3         b      3
4         c      4
       name  data2
0  ZhangFei      0
1    GuanYu      1
2         A      2
3         B      3
4         C      4
       name  data1  data2
0  ZhangFei      0      0
1    GuanYu      1      1


2. inner 内连接

inner 内链接是 merge 合并的默认情况，inner 内连接其实也就是键的交集，在这里 df1, df2 相同的键是 name，所以是基于 name 字段做的连接

In [54]:
df3 = pd.merge(df1, df2, how='inner')
print(df3)

name  data1  data2
0  ZhangFei      0      0
1    GuanYu      1      1


3. left 左连接

In [55]:
df3 = pd.merge(df1, df2, how='left')
print(df3)

name  data1  data2
0  ZhangFei      0    0.0
1    GuanYu      1    1.0
2         a      2    NaN
3         b      3    NaN
4         c      4    NaN


4. right 右连接

In [56]:
df3 = pd.merge(df1, df2, how='right')
print(df3)

name  data1  data2
0  ZhangFei    0.0      0
1    GuanYu    1.0      1
2         A    NaN      2
3         B    NaN      3
4         C    NaN      4


5. outer 外连接

In [57]:
df3 = pd.merge(df1, df2, how='outer')
print(df3)

name  data1  data2
0  ZhangFei    0.0    0.0
1    GuanYu    1.0    1.0
2         a    2.0    NaN
3         b    3.0    NaN
4         c    4.0    NaN
5         A    NaN    2.0
6         B    NaN    3.0
7         C    NaN    4.0


## 如何用 SQL 方式打开 Pandas
工具：pandasql

In [1]:

import pandas as pd
from pandas import DataFrame
from pandasql import sqldf, load_meat, load_births
df1 = DataFrame({'name':['ZhangFei', 'GuanYu', 'a', 'b', 'c'], 'data1':range(5)})
# lambda argument_list: expression
pysqldf = lambda sql: sqldf(sql, globals()) # 输入的参数是 sql，返回的结果是 sqldf 对 sql 的运行结果，当然 sqldf 中也输入了 globals 全局参数，因为在 sql 中有对全局参数 df1 的使用
sql = "select * from df1 where name ='ZhangFei'"
print (pysqldf(sql))

name  data1
0  ZhangFei      0
